### ISSUE TITLE
Create view and edit pages for stories

### ISSUE THREAD

**Issue by Dafondo** [unc-cs-sg/myhealthed-admin#4]

**Comment by nikhil-vytla** [comment]
**Story Detailed View**

- When an individual story is expanded to view or edit, each story must include the following information:
  - Story ID
  - Date submitted
  - Topic 
  - **Story prompt title**
  - User demographic information
  - Story text
  - **Checklist of publication criteria**
  - Status (needs review, rejected for publication, approved for publication)
  - Date published or scheduled to be published (if applicable)

- The following aspects of an individual story must be modifiable:
  - Story text - edit the text, add or **delete number of text bubbles**, and change the order of text bubbles
  - **Checklist of publication criteria - to document reasons for rejection (if applicable)**
  - Status - modified to update the status after reviewing

- If a story is rejected for publication, must be able to provide feedback regarding why it was rejected

- If a story is approved for publication, additional information needs to be included and modifiable:
  - Story preview text (a story snippet that shows up as the story preview in the app)
  - Story tags
  - **Link resource - search from list of existing resources or be able to add a new link resource (including site name, link name, and link URL) that is then added to the existing link resource database**
  - Publication date

- **When viewing an individual story submission, should also be able to go “back” to the previous page after viewing or making changes. This is especially important when the user is viewing a filtered story list view and needs to go back to the same filtered list view after viewing an individual story.**
