### ISSUE TITLE
Cleanup packages

### ISSUE THREAD

**Issue by jasontyu** [unc-cs-sg/myhealthed-admin#7]
`npm install` took 2 minutes and threw a bunch of warnings, including a security vulnerability. See below for screenshots from my terminal.

<img width="348" alt="Screen Shot 2020-03-26 at 5 31 00 PM" src="https://user-images.githubusercontent.com/18102685/77698853-b53a8200-6f87-11ea-9bc3-5a7be55cd8ce.png">
<img width="570" alt="Screen Shot 2020-03-26 at 5 31 34 PM" src="https://user-images.githubusercontent.com/18102685/77698858-b7044580-6f87-11ea-8cca-2dc14631d5d7.png">
<img width="570" alt="Screen Shot 2020-03-26 at 5 31 44 PM" src="https://user-images.githubusercontent.com/18102685/77698864-b8ce0900-6f87-11ea-869f-9a80f7b32e2b.png">
<img width="569" alt="Screen Shot 2020-03-26 at 5 32 08 PM" src="https://user-images.githubusercontent.com/18102685/77698867-ba97cc80-6f87-11ea-873b-68ddde17b9e0.png">
<img width="229" alt="Screen Shot 2020-03-26 at 5 32 12 PM" src="https://user-images.githubusercontent.com/18102685/77698872-bbc8f980-6f87-11ea-8b01-d72780765265.png">

**Comment by Dafondo** [comment]
Closing this issue.
Most packages have been cleaned up in #22. One security vulnerability in Airframe needs manual review, but likely does not affect us.
